FROM golang:1.21.1-alpine

WORKDIR /usr/src/app

COPY . .

# Compilar la aplicación
RUN go build -o datanode datanode.go

# Exponer el puerto en el que escucha el servidor gRPC
EXPOSE 50000

# Ejecutar la aplicación compilada
CMD ["./datanode"]